import { Restaurant } from './Restaurant';

export const mockRestaurants: Record<string, Restaurant> = {
  'fancy-food': {
    id: 'fancy-food',
    name: 'Fancy Food',
    address: '34 Paul-Henri Spaak Street',
    tables: 10,
    tableSize: 2,
    openingTime: 1700,
    closingTime: 2300,
    reservationTimeMinutes: 60,
    reservations: {},
  },
  'antonio-mozzi': {
    id: 'antonio-mozzi',
    name: 'Antonio Mozzi',
    address: '75 Alcide de Gasperi Street',
    tables: 15,
    tableSize: 2,
    openingTime: 1700,
    closingTime: 2300,
    reservationTimeMinutes: 90,
    reservations: {},
  },
  'eat-me': {
    id: 'eat-me',
    name: 'Eat Me',
    address: '63 Schuman Street',
    tables: 4,
    tableSize: 3,
    openingTime: 1700,
    closingTime: 2300,
    reservationTimeMinutes: 45,
    reservations: {},
  },
  cindirella: {
    id: 'cindirella',
    name: 'Cindirella',
    address: '88 Louise Weiss Street',
    tables: 20,
    tableSize: 2,
    openingTime: 1700,
    closingTime: 2300,
    reservationTimeMinutes: 60,
    reservations: {},
  },
  'sushi-and-sushi': {
    id: 'sushi-and-sushi',
    name: 'Sushi & Sushi',
    address: '19 Adenauer Street',
    tables: 12,
    tableSize: 2,
    openingTime: 1700,
    closingTime: 2300,
    reservationTimeMinutes: 45,
    reservations: {},
  },
};

export const mockMyRestaurantId = 'antonio-mozzi';